import { StudentIntelligence } from "./types";

export const initialStudentIntelligenceMap: Record<string, StudentIntelligence> = {
  // -------------------------------------------------------------
  // STUDENT 1: Arun Kumar (Declining Student / High Risk Trajectory)
  // -------------------------------------------------------------
  "s1": {
    studentId: "s1",
    profile: {
      id: "s1",
      name: "Arun Kumar",
      role: "student",
      course: "B.Tech IT",
      year: "3rd Year",
      department: "Information Technology",
      attendancePercent: 65,
      quizAverage: 49,
      assignmentAverage: 72,
      lateSubmissions: 2,
      totalAssignments: 10,
      weakTopics: ["DBMS Normalization", "SQL Joins", "Transactions"],
      email: "arun.kumar@campus.edu",
      enrolledSubjects: ["Database Management Systems", "Operating Systems", "Computer Networks", "Software Engineering"],
      gpa: 2.8,
      guardianContact: "+91 98765 43210",
      assignedMentorId: "f1",
      assignedMentorName: "Prof. Rahul Kumar",
      journeyType: "declining",
    },
    successScore: 54,
    riskLevel: "HIGH",
    academicMetrics: {
      quizAverage: 49,
      assignmentAverage: 72,
      attendancePercent: 65,
      gpa: 2.8,
      subjectScores: [
        { subject: "Database Management Systems", quizAvg: 45, assignmentAvg: 68, attendancePercent: 60, score: 55, total: 100, status: "critical" },
        { subject: "Operating Systems", quizAvg: 70, assignmentAvg: 75, attendancePercent: 72, score: 72, total: 100, status: "warning" },
        { subject: "Computer Networks", quizAvg: 62, assignmentAvg: 70, attendancePercent: 68, score: 67, total: 100, status: "warning" },
        { subject: "Software Engineering", quizAvg: 76, assignmentAvg: 80, attendancePercent: 75, score: 77, total: 100, status: "good" },
      ],
      weakTopics: [
        { id: "sql-joins", name: "SQL Joins", priority: "high", subject: "Database Management Systems", description: "INNER, LEFT, RIGHT and FULL OUTER joins" },
        { id: "normalization", name: "DBMS Normalization", priority: "high", subject: "Database Management Systems", description: "1NF, 2NF, 3NF and BCNF dependencies" },
        { id: "transactions", name: "Transactions & Concurrency", priority: "medium", subject: "Database Management Systems", description: "ACID properties & deadlocks" },
      ],
      totalAssignments: 10,
      completedAssignments: 8,
      lateSubmissions: 2,
      missedQuizzes: 1,
      examsAverage: 58,
      academicRiskScore: 68,
    },
    engagementMetrics: {
      activeDaysLast30Days: 14,
      currentStreak: 2,
      longestStreak: 7,
      aiTutorInteractionsCount: 18,
      totalXP: 1840,
      arenaCoins: 1250,
      learningLevel: 12,
      questsCompleted: 12,
      materialsAccessedCount: 9,
      totalTimeSpentMinutes: 420,
      weeklyActiveHours: 3.5,
      engagementScore: 52,
      engagementTrend: "declining",
    },
    behaviorMetrics: {
      submissionPunctualityRate: 75,
      quizAttemptRate: 85,
      recoveryPlanAdherence: 35,
      helpSeekingFrequency: "moderate",
      studyConsistencyScore: 48,
      loginFrequencyPerWeek: 3,
      feedbackSubmittedCount: 1,
      behaviorScore: 58,
    },
    supportInteractions: {
      mentorRequests: [
        {
          id: "mr_1",
          studentId: "s1",
          mentorId: "f1",
          subject: "DBMS Normalization Help",
          date: "2026-10-15",
          time: "16:30",
          status: "pending",
        },
      ],
      supportTickets: [
        {
          id: "st_1",
          creatorId: "s1",
          category: "Academic",
          description: "Requesting re-evaluation for DBMS Assignment 2",
          status: "pending",
          createdAt: "2026-10-02T10:00:00Z",
        },
      ],
      facultySessionsCount: 2,
      lastMentorSessionDate: "2026-09-20",
      unresolvedIssuesCount: 2,
      mentorFeedbackCount: 1,
    },
    learningActivity: {
      recentActivities: [
        { id: "act-1", type: "quiz", title: "Completed Database Fundamentals Quiz", detail: "Scored 45%", timestamp: "2 hours ago", subject: "DBMS", score: 45 },
        { id: "act-2", type: "study", title: "Viewed SQL Joins Study Material", detail: "Read 15%", timestamp: "5 hours ago", subject: "DBMS" },
        { id: "act-3", type: "assignment", title: "Submitted DBMS Assignment 2", detail: "Late submission (+1 day)", timestamp: "1 day ago", subject: "DBMS" },
        { id: "act-4", type: "tutor", title: "Asked AI Tutor: 'What is BCNF?'", detail: "AI Tutor Chat", timestamp: "1 day ago", subject: "DBMS" },
      ],
      recoveryPlan: {
        title: "DBMS 7-Day Recovery Plan",
        focus: "SQL Joins & Normalization",
        days: 7,
        tasksCompleted: 2,
        totalTasks: 8,
        progressPercent: 25,
        status: "in_progress",
        currentDay: 2,
      },
      adaptiveQuizCount: 4,
      arenaBattlesCompleted: 15,
      skillsMasteredCount: 3,
    },
    trends: {
      weekly: [
        { week: "Week 1", date: "2026-08-18", quizAverage: 72, assignmentAverage: 82, attendancePercent: 82, engagementScore: 78, successScore: 78, riskScore: 20 },
        { week: "Week 2", date: "2026-08-25", quizAverage: 68, assignmentAverage: 78, attendancePercent: 78, engagementScore: 72, successScore: 74, riskScore: 26 },
        { week: "Week 3", date: "2026-09-01", quizAverage: 64, assignmentAverage: 75, attendancePercent: 74, engagementScore: 65, successScore: 70, riskScore: 32 },
        { week: "Week 4", date: "2026-09-08", quizAverage: 58, assignmentAverage: 74, attendancePercent: 70, engagementScore: 60, successScore: 65, riskScore: 42 },
        { week: "Week 5", date: "2026-09-15", quizAverage: 52, assignmentAverage: 73, attendancePercent: 68, engagementScore: 56, successScore: 60, riskScore: 52 },
        { week: "Week 6", date: "2026-09-22", quizAverage: 49, assignmentAverage: 72, attendancePercent: 65, engagementScore: 52, successScore: 54, riskScore: 64 },
      ],
      quizTrendDelta: -23,
      assignmentTrendDelta: -10,
      attendanceTrendDelta: -17,
      engagementTrendDelta: -26,
      overallDirection: "declining",
    },
    riskFactors: [
      { factorId: "rf_1", category: "attendance", title: "Low Attendance Warning", description: "Attendance dropped to 65% (below 75% threshold)", impact: "high", weight: 30, status: "active" },
      { factorId: "rf_2", category: "academic", title: "Severe Quiz Drop in DBMS", description: "DBMS Quiz score dropped to 45%", impact: "high", weight: 25, status: "active" },
      { factorId: "rf_3", category: "behavior", title: "Repeated Late Submissions", description: "2 assignments submitted past deadline", impact: "medium", weight: 15, status: "active" },
      { factorId: "rf_4", category: "engagement", title: "Recovery Plan Stalled", description: "Only 25% of Recovery Plan tasks completed", impact: "medium", weight: 15, status: "active" },
    ],
    studentRisk: {
      overallRiskLevel: "HIGH",
      riskScore: 64,
      academicRisk: 68,
      attendanceRisk: 70,
      engagementRisk: 55,
      behaviorRisk: 48,
      contributingFactors: [], // resolved dynamically by service
      riskTrend: "worsening",
      primaryRiskDriver: "Low DBMS attendance & failing quiz scores",
    },
    journey: [
      { id: "je_1", studentId: "s1", timestamp: "2026-08-18T09:00:00Z", date: "2026-08-18", category: "academic", title: "Semester Enrolled", description: "Enrolled in B.Tech IT 3rd Year semester courses", severity: "info" },
      { id: "je_2", studentId: "s1", timestamp: "2026-08-28T11:00:00Z", date: "2026-08-28", category: "academic", title: "Good DBMS Start", description: "Scored 72% on DBMS ER-Modeling diagnostic quiz", severity: "positive" },
      { id: "je_3", studentId: "s1", timestamp: "2026-09-10T14:30:00Z", date: "2026-09-10", category: "attendance", title: "Attendance Warning Issued", description: "Attendance dropped to 70% in DBMS lectures", severity: "warning" },
      { id: "je_4", studentId: "s1", timestamp: "2026-09-18T16:00:00Z", date: "2026-09-18", category: "academic", title: "Critical Quiz Drop", description: "DBMS Normalization quiz average fell to 49%", severity: "critical" },
      { id: "je_5", studentId: "s1", timestamp: "2026-09-20T10:00:00Z", date: "2026-09-20", category: "intervention", title: "7-Day Recovery Plan Assigned", description: "System generated targeted recovery plan for SQL Joins & Normalization", severity: "warning" },
      { id: "je_6", studentId: "s1", timestamp: "2026-10-01T15:00:00Z", date: "2026-10-01", category: "support", title: "Mentor Request Filed", description: "Requested 1-on-1 tutoring with Prof. Rahul Kumar", severity: "info" },
    ],
    recommendedInterventions: [
      {
        id: "int_1",
        studentId: "s1",
        title: "1-on-1 DBMS Remedial Mentoring",
        description: "Schedule a mandatory 45-minute tutoring session with Prof. Rahul Kumar focusing on SQL Joins & Normalization.",
        category: "mentor_session",
        suggestedBy: "AI_ENGINE",
        priority: "high",
        status: "recommended",
        createdAt: "2026-10-02T10:00:00Z",
        targetCompletionDate: "2026-10-15",
        assignedTo: "Prof. Rahul Kumar",
      },
      {
        id: "int_2",
        studentId: "s1",
        title: "Intensive 7-Day DBMS Recovery Plan",
        description: "Complete all remaining daily modules in the DBMS recovery plan including practice quizzes.",
        category: "recovery_plan",
        suggestedBy: "SYSTEM",
        priority: "high",
        status: "in_progress",
        createdAt: "2026-09-20T10:00:00Z",
        targetCompletionDate: "2026-10-10",
      },
      {
        id: "int_3",
        studentId: "s1",
        title: "Attendance Monitoring Alert",
        description: "Notify student & faculty advisor to ensure attendance reaches >75% over next 2 weeks.",
        category: "attendance_warning",
        suggestedBy: "AI_ENGINE",
        priority: "medium",
        status: "recommended",
        createdAt: "2026-10-01T12:00:00Z",
      },
    ],
    interventionHistory: [
      {
        intervention: {
          id: "int_hist_1",
          studentId: "s1",
          title: "DBMS Diagnostic Quiz Re-take",
          description: "Re-take foundational DBMS quiz to identify knowledge gaps.",
          category: "academic_tutoring",
          suggestedBy: "AI_ENGINE",
          priority: "medium",
          status: "completed",
          createdAt: "2026-09-12T10:00:00Z",
        },
        outcome: {
          id: "out_1",
          interventionId: "int_hist_1",
          studentId: "s1",
          recordedAt: "2026-09-16T14:00:00Z",
          outcomeStatus: "partially_successful",
          impactMetrics: { scoreImprovement: 8, riskScoreDelta: -4 },
          notes: "Improved basic syntax score, but normalization concepts remain unmastered.",
          evaluatedBy: "AI Tutor Engine",
        },
      },
    ],
    placementReadiness: {
      aptitudeScore: 52,
      codingScore: 48,
      mockInterviewScore: 45,
      resumeStatus: "in_progress",
      placementAssessmentsCompleted: 2,
      preparationProgressPercent: 42,
      overallPlacementScore: 48,
      status: "needs_preparation",
    },
    lmsActivity: {
      totalLogins: 28,
      assignmentsSubmitted: 8,
      assignmentCompletionRate: 80,
      activeDaysLast30: 14,
      averageSessionDurationMins: 22,
      lastLoginDate: "2026-10-06",
      lmsScore: 62,
    },
    skillsAndFeedback: {
      technicalSkills: [
        { name: "SQL", score: 55 },
        { name: "OS Fundamentals", score: 68 },
        { name: "Computer Networks", score: 62 },
      ],
      assessmentsPassedCount: 2,
      facultyFeedbackCount: 2,
      recentFacultyNotes: "Needs DBMS lab attendance and SQL query optimization review.",
      skillsScore: 61,
    },
    campusEngagement: {
      eventsAttendedCount: 1,
      clubParticipationsCount: 1,
      hackathonsCount: 0,
      certificationsCount: 0,
      engagementScore: 40,
    },
  },

  // -------------------------------------------------------------
  // STUDENT 2: Ananya Roy (Stable / High-Performing Student)
  // -------------------------------------------------------------
  "s2": {
    studentId: "s2",
    profile: {
      id: "s2",
      name: "Ananya Roy",
      role: "student",
      course: "B.Tech CSE",
      year: "3rd Year",
      department: "Computer Science",
      attendancePercent: 95,
      quizAverage: 92,
      assignmentAverage: 94,
      lateSubmissions: 0,
      totalAssignments: 12,
      weakTopics: [],
      email: "ananya.roy@campus.edu",
      enrolledSubjects: ["Data Structures & Algorithms", "Operating Systems", "Computer Networks", "Compiler Design"],
      gpa: 3.9,
      guardianContact: "+91 98765 11111",
      assignedMentorId: "f2",
      assignedMentorName: "Prof. Priya Sharma",
      journeyType: "stable",
    },
    successScore: 94,
    riskLevel: "LOW",
    academicMetrics: {
      quizAverage: 92,
      assignmentAverage: 94,
      attendancePercent: 95,
      gpa: 3.9,
      subjectScores: [
        { subject: "Data Structures & Algorithms", quizAvg: 95, assignmentAvg: 96, attendancePercent: 96, score: 96, total: 100, status: "good" },
        { subject: "Operating Systems", quizAvg: 90, assignmentAvg: 92, attendancePercent: 94, score: 92, total: 100, status: "good" },
        { subject: "Computer Networks", quizAvg: 92, assignmentAvg: 95, attendancePercent: 95, score: 94, total: 100, status: "good" },
        { subject: "Compiler Design", quizAvg: 89, assignmentAvg: 92, attendancePercent: 95, score: 91, total: 100, status: "good" },
      ],
      weakTopics: [],
      totalAssignments: 12,
      completedAssignments: 12,
      lateSubmissions: 0,
      missedQuizzes: 0,
      examsAverage: 94,
      academicRiskScore: 5,
    },
    engagementMetrics: {
      activeDaysLast30Days: 28,
      currentStreak: 14,
      longestStreak: 21,
      aiTutorInteractionsCount: 42,
      totalXP: 3450,
      arenaCoins: 2800,
      learningLevel: 18,
      questsCompleted: 24,
      materialsAccessedCount: 22,
      totalTimeSpentMinutes: 980,
      weeklyActiveHours: 8.2,
      engagementScore: 95,
      engagementTrend: "stable",
    },
    behaviorMetrics: {
      submissionPunctualityRate: 100,
      quizAttemptRate: 100,
      recoveryPlanAdherence: 100,
      helpSeekingFrequency: "high",
      studyConsistencyScore: 96,
      loginFrequencyPerWeek: 7,
      feedbackSubmittedCount: 4,
      behaviorScore: 96,
    },
    supportInteractions: {
      mentorRequests: [],
      supportTickets: [],
      facultySessionsCount: 5,
      lastMentorSessionDate: "2026-10-01",
      unresolvedIssuesCount: 0,
      mentorFeedbackCount: 3,
    },
    learningActivity: {
      recentActivities: [
        { id: "act-s2-1", type: "arena", title: "Won Data Structures Arena Duel", detail: "Score 100%", timestamp: "1 hour ago", subject: "DSA", score: 100 },
        { id: "act-s2-2", type: "quiz", title: "Completed Compiler Design Master Quiz", detail: "Score 92%", timestamp: "4 hours ago", subject: "Compiler Design", score: 92 },
        { id: "act-s2-3", type: "tutor", title: "Asked AI Tutor: 'Advanced LR Parsing Algorithms'", detail: "AI Tutor Session", timestamp: "Yesterday" },
      ],
      recoveryPlan: {
        title: "No Active Recovery Plan Needed",
        focus: "Advanced Honors Track",
        days: 0,
        tasksCompleted: 0,
        totalTasks: 0,
        progressPercent: 100,
        status: "completed",
        currentDay: 0,
      },
      adaptiveQuizCount: 15,
      arenaBattlesCompleted: 38,
      skillsMasteredCount: 12,
    },
    trends: {
      weekly: [
        { week: "Week 1", date: "2026-08-18", quizAverage: 90, assignmentAverage: 92, attendancePercent: 94, engagementScore: 92, successScore: 92, riskScore: 8 },
        { week: "Week 2", date: "2026-08-25", quizAverage: 91, assignmentAverage: 93, attendancePercent: 95, engagementScore: 93, successScore: 93, riskScore: 7 },
        { week: "Week 3", date: "2026-09-01", quizAverage: 92, assignmentAverage: 94, attendancePercent: 95, engagementScore: 94, successScore: 94, riskScore: 6 },
        { week: "Week 4", date: "2026-09-08", quizAverage: 92, assignmentAverage: 94, attendancePercent: 95, engagementScore: 95, successScore: 94, riskScore: 5 },
        { week: "Week 5", date: "2026-09-15", quizAverage: 93, assignmentAverage: 95, attendancePercent: 96, engagementScore: 95, successScore: 95, riskScore: 4 },
        { week: "Week 6", date: "2026-09-22", quizAverage: 92, assignmentAverage: 94, attendancePercent: 95, engagementScore: 95, successScore: 94, riskScore: 5 },
      ],
      quizTrendDelta: 2,
      assignmentTrendDelta: 2,
      attendanceTrendDelta: 1,
      engagementTrendDelta: 3,
      overallDirection: "stable",
    },
    riskFactors: [],
    studentRisk: {
      overallRiskLevel: "LOW",
      riskScore: 5,
      academicRisk: 5,
      attendanceRisk: 4,
      engagementRisk: 5,
      behaviorRisk: 4,
      contributingFactors: [],
      riskTrend: "stable",
      primaryRiskDriver: "None - Excellent overall performance",
    },
    journey: [
      { id: "je_s2_1", studentId: "s2", timestamp: "2026-08-18T09:00:00Z", date: "2026-08-18", category: "academic", title: "Semester Enrolled", description: "Enrolled in B.Tech CSE 3rd Year", severity: "info" },
      { id: "je_s2_2", studentId: "s2", timestamp: "2026-09-05T14:00:00Z", date: "2026-09-05", category: "engagement", title: "Consistency Champion Award", description: "Achieved 14-day continuous learning streak", severity: "positive" },
      { id: "je_s2_3", studentId: "s2", timestamp: "2026-09-20T11:00:00Z", date: "2026-09-20", category: "academic", title: "Top Scorer in Mid-Terms", description: "Scored 96% in Data Structures & Algorithms", severity: "positive" },
    ],
    recommendedInterventions: [
      {
        id: "int_s2_1",
        studentId: "s2",
        title: "Peer Tutor Leadership Nomination",
        description: "Nominate Ananya as a peer mentor for junior students in Data Structures.",
        category: "peer_study",
        suggestedBy: "AI_ENGINE",
        priority: "low",
        status: "recommended",
        createdAt: "2026-10-01T10:00:00Z",
      },
      {
        id: "int_s2_2",
        studentId: "s2",
        title: "Advanced Research Track Recommendation",
        description: "Recommend enrollment in Advanced Compiler Optimization research group.",
        category: "academic_tutoring",
        suggestedBy: "FACULTY",
        priority: "low",
        status: "recommended",
        createdAt: "2026-10-03T10:00:00Z",
        assignedTo: "Prof. Priya Sharma",
      },
    ],
    interventionHistory: [],
    placementReadiness: {
      aptitudeScore: 94,
      codingScore: 92,
      mockInterviewScore: 90,
      resumeStatus: "verified",
      placementAssessmentsCompleted: 6,
      preparationProgressPercent: 95,
      overallPlacementScore: 93,
      status: "ready",
    },
    lmsActivity: {
      totalLogins: 72,
      assignmentsSubmitted: 12,
      assignmentCompletionRate: 100,
      activeDaysLast30: 29,
      averageSessionDurationMins: 45,
      lastLoginDate: "2026-10-10",
      lmsScore: 96,
    },
    skillsAndFeedback: {
      technicalSkills: [
        { name: "Data Structures", score: 95 },
        { name: "System Design", score: 88 },
        { name: "React & TypeScript", score: 92 },
      ],
      assessmentsPassedCount: 8,
      facultyFeedbackCount: 4,
      recentFacultyNotes: "Exceptional analytical thinking; recommended for campus hackathon mentor.",
      skillsScore: 94,
    },
    campusEngagement: {
      eventsAttendedCount: 5,
      clubParticipationsCount: 2,
      hackathonsCount: 3,
      certificationsCount: 2,
      engagementScore: 92,
    },
  },

  // -------------------------------------------------------------
  // STUDENT 3: Rahul Verma (Improving Student)
  // -------------------------------------------------------------
  "s3": {
    studentId: "s3",
    profile: {
      id: "s3",
      name: "Rahul Verma",
      role: "student",
      course: "B.Tech ECE",
      year: "2nd Year",
      department: "Electronics & Communication",
      attendancePercent: 79,
      quizAverage: 74,
      assignmentAverage: 78,
      lateSubmissions: 1,
      totalAssignments: 9,
      weakTopics: ["Fourier Transform"],
      email: "rahul.verma@campus.edu",
      enrolledSubjects: ["Signals & Systems", "Digital Electronics", "Circuit Theory", "Engineering Mathematics"],
      gpa: 3.2,
      guardianContact: "+91 98765 22222",
      assignedMentorId: "f2",
      assignedMentorName: "Prof. Priya Sharma",
      journeyType: "improving",
    },
    successScore: 76,
    riskLevel: "LOW",
    academicMetrics: {
      quizAverage: 74,
      assignmentAverage: 78,
      attendancePercent: 79,
      gpa: 3.2,
      subjectScores: [
        { subject: "Signals & Systems", quizAvg: 72, assignmentAvg: 75, attendancePercent: 78, score: 75, total: 100, status: "warning" },
        { subject: "Digital Electronics", quizAvg: 80, assignmentAvg: 82, attendancePercent: 82, score: 81, total: 100, status: "good" },
        { subject: "Circuit Theory", quizAvg: 75, assignmentAvg: 78, attendancePercent: 78, score: 77, total: 100, status: "good" },
        { subject: "Engineering Mathematics", quizAvg: 69, assignmentAvg: 75, attendancePercent: 76, score: 73, total: 100, status: "warning" },
      ],
      weakTopics: [
        { id: "fourier-transform", name: "Fourier Transform Applications", priority: "medium", subject: "Signals & Systems", description: "Continuous and Discrete Fourier Transforms" },
      ],
      totalAssignments: 9,
      completedAssignments: 8,
      lateSubmissions: 1,
      missedQuizzes: 0,
      examsAverage: 75,
      academicRiskScore: 32,
    },
    engagementMetrics: {
      activeDaysLast30Days: 20,
      currentStreak: 5,
      longestStreak: 9,
      aiTutorInteractionsCount: 26,
      totalXP: 2200,
      arenaCoins: 1600,
      learningLevel: 14,
      questsCompleted: 15,
      materialsAccessedCount: 14,
      totalTimeSpentMinutes: 580,
      weeklyActiveHours: 5.0,
      engagementScore: 78,
      engagementTrend: "improving",
    },
    behaviorMetrics: {
      submissionPunctualityRate: 88,
      quizAttemptRate: 100,
      recoveryPlanAdherence: 85,
      helpSeekingFrequency: "high",
      studyConsistencyScore: 76,
      loginFrequencyPerWeek: 5,
      feedbackSubmittedCount: 2,
      behaviorScore: 82,
    },
    supportInteractions: {
      mentorRequests: [
        {
          id: "mr_s3_1",
          studentId: "s3",
          mentorId: "f2",
          subject: "Fourier Transform Doubts",
          date: "2026-09-25",
          time: "15:00",
          status: "completed",
        },
      ],
      supportTickets: [],
      facultySessionsCount: 3,
      lastMentorSessionDate: "2026-09-25",
      unresolvedIssuesCount: 0,
      mentorFeedbackCount: 2,
    },
    learningActivity: {
      recentActivities: [
        { id: "act-s3-1", type: "quiz", title: "Completed Signals & Systems Re-quiz", detail: "Scored 78%", timestamp: "3 hours ago", subject: "Signals & Systems", score: 78 },
        { id: "act-s3-2", type: "recovery", title: "Completed Recovery Task 5/6", detail: "Fourier Analysis", timestamp: "Yesterday", subject: "Signals & Systems" },
        { id: "act-s3-3", type: "tutor", title: "Asked AI Tutor: 'Inverse Fourier Transform Steps'", detail: "AI Tutor", timestamp: "2 days ago" },
      ],
      recoveryPlan: {
        title: "Signals & Systems Recovery Plan",
        focus: "Fourier Transform & Laplace Basics",
        days: 7,
        tasksCompleted: 6,
        totalTasks: 7,
        progressPercent: 86,
        status: "in_progress",
        currentDay: 6,
      },
      adaptiveQuizCount: 8,
      arenaBattlesCompleted: 22,
      skillsMasteredCount: 7,
    },
    trends: {
      weekly: [
        { week: "Week 1", date: "2026-08-18", quizAverage: 54, assignmentAverage: 65, attendancePercent: 68, engagementScore: 58, successScore: 60, riskScore: 55 },
        { week: "Week 2", date: "2026-08-25", quizAverage: 58, assignmentAverage: 68, attendancePercent: 70, engagementScore: 62, successScore: 64, riskScore: 48 },
        { week: "Week 3", date: "2026-09-01", quizAverage: 62, assignmentAverage: 72, attendancePercent: 73, engagementScore: 68, successScore: 68, riskScore: 42 },
        { week: "Week 4", date: "2026-09-08", quizAverage: 68, assignmentAverage: 75, attendancePercent: 75, engagementScore: 72, successScore: 72, riskScore: 35 },
        { week: "Week 5", date: "2026-09-15", quizAverage: 71, assignmentAverage: 77, attendancePercent: 78, engagementScore: 75, successScore: 74, riskScore: 30 },
        { week: "Week 6", date: "2026-09-22", quizAverage: 74, assignmentAverage: 78, attendancePercent: 79, engagementScore: 78, successScore: 76, riskScore: 25 },
      ],
      quizTrendDelta: 20,
      assignmentTrendDelta: 13,
      attendanceTrendDelta: 11,
      engagementTrendDelta: 20,
      overallDirection: "improving",
    },
    riskFactors: [
      { factorId: "rf_s3_1", category: "academic", title: "Residual Weak Topic: Fourier Transform", description: "Requires final mastery check to confirm recovery", impact: "low", weight: 10, status: "mitigated" },
    ],
    studentRisk: {
      overallRiskLevel: "LOW",
      riskScore: 25,
      academicRisk: 32,
      attendanceRisk: 22,
      engagementRisk: 20,
      behaviorRisk: 18,
      contributingFactors: [],
      riskTrend: "improving",
      primaryRiskDriver: "Positive trajectory - Recovering from early semester drop",
    },
    journey: [
      { id: "je_s3_1", studentId: "s3", timestamp: "2026-08-18T09:00:00Z", date: "2026-08-18", category: "academic", title: "Semester Enrolled", description: "Enrolled in B.Tech ECE 2nd Year", severity: "info" },
      { id: "je_s3_2", studentId: "s3", timestamp: "2026-08-26T10:00:00Z", date: "2026-08-26", category: "academic", title: "Early Low Quiz Score", description: "Scored 54% in Signals & Systems Quiz 1", severity: "warning" },
      { id: "je_s3_3", studentId: "s3", timestamp: "2026-09-02T16:00:00Z", date: "2026-09-02", category: "intervention", title: "Enrolled in Signals Recovery Plan", description: "Started 7-day Fourier Transform practice track", severity: "info" },
      { id: "je_s3_4", studentId: "s3", timestamp: "2026-09-25T15:00:00Z", date: "2026-09-25", category: "support", title: "Attended Mentor Session", description: "Completed 1-on-1 tutoring session with Prof. Priya Sharma", severity: "positive" },
      { id: "je_s3_5", studentId: "s3", timestamp: "2026-09-28T11:00:00Z", date: "2026-09-28", category: "academic", title: "Quiz Score Recovery", description: "Signals & Systems re-quiz score jumped to 78%", severity: "positive" },
    ],
    recommendedInterventions: [
      {
        id: "int_s3_1",
        studentId: "s3",
        title: "Final Fourier Transform Mastery Assessment",
        description: "Complete 10-question adaptive quiz to confirm 100% mastery of Fourier concepts.",
        category: "adaptive_quiz",
        suggestedBy: "AI_ENGINE",
        priority: "low",
        status: "recommended",
        createdAt: "2026-10-02T10:00:00Z",
      },
    ],
    interventionHistory: [
      {
        intervention: {
          id: "int_s3_h1",
          studentId: "s3",
          title: "Signals & Systems Remedial Support",
          description: "Mentor session and practice problem set.",
          category: "mentor_session",
          suggestedBy: "AI_ENGINE",
          priority: "high",
          status: "completed",
          createdAt: "2026-09-02T10:00:00Z",
        },
        outcome: {
          id: "out_s3_1",
          interventionId: "int_s3_h1",
          studentId: "s3",
          recordedAt: "2026-09-26T10:00:00Z",
          outcomeStatus: "successful",
          impactMetrics: { scoreImprovement: 24, attendanceChange: 11, riskScoreDelta: -30 },
          notes: "Student demonstrated strong recovery after mentor session and recovery plan.",
          evaluatedBy: "Prof. Priya Sharma",
        },
      },
    ],
    placementReadiness: {
      aptitudeScore: 62,
      codingScore: 54,
      mockInterviewScore: 50,
      resumeStatus: "in_progress",
      placementAssessmentsCompleted: 2,
      preparationProgressPercent: 50,
      overallPlacementScore: 54,
      status: "needs_preparation",
    },
    lmsActivity: {
      totalLogins: 48,
      assignmentsSubmitted: 8,
      assignmentCompletionRate: 88,
      activeDaysLast30: 20,
      averageSessionDurationMins: 32,
      lastLoginDate: "2026-10-09",
      lmsScore: 78,
    },
    skillsAndFeedback: {
      technicalSkills: [
        { name: "Signals & Systems", score: 72 },
        { name: "Digital Logic", score: 80 },
        { name: "C++ Programming", score: 65 },
      ],
      assessmentsPassedCount: 4,
      facultyFeedbackCount: 2,
      recentFacultyNotes: "Good theoretical concepts; recommend dedicated coding interview drills.",
      skillsScore: 74,
    },
    campusEngagement: {
      eventsAttendedCount: 3,
      clubParticipationsCount: 1,
      hackathonsCount: 1,
      certificationsCount: 1,
      engagementScore: 70,
    },
  },

  // -------------------------------------------------------------
  // STUDENT 4: Priya Nair (High-Risk Student)
  // -------------------------------------------------------------
  "s4": {
    studentId: "s4",
    profile: {
      id: "s4",
      name: "Priya Nair",
      role: "student",
      course: "B.Tech IT",
      year: "3rd Year",
      department: "Information Technology",
      attendancePercent: 52,
      quizAverage: 41,
      assignmentAverage: 48,
      lateSubmissions: 4,
      totalAssignments: 8,
      weakTopics: ["Web Development", "Data Structures", "DBMS", "Java OOP"],
      email: "priya.nair@campus.edu",
      enrolledSubjects: ["Database Management Systems", "Web Technologies", "Java Programming", "Software Testing"],
      gpa: 2.1,
      guardianContact: "+91 98765 33333",
      assignedMentorId: "f1",
      assignedMentorName: "Prof. Rahul Kumar",
      journeyType: "high_risk",
    },
    successScore: 40,
    riskLevel: "CRITICAL",
    academicMetrics: {
      quizAverage: 41,
      assignmentAverage: 48,
      attendancePercent: 52,
      gpa: 2.1,
      subjectScores: [
        { subject: "Database Management Systems", quizAvg: 38, assignmentAvg: 45, attendancePercent: 50, score: 44, total: 100, status: "critical" },
        { subject: "Web Technologies", quizAvg: 42, assignmentAvg: 50, attendancePercent: 55, score: 48, total: 100, status: "critical" },
        { subject: "Java Programming", quizAvg: 40, assignmentAvg: 46, attendancePercent: 50, score: 45, total: 100, status: "critical" },
        { subject: "Software Testing", quizAvg: 44, assignmentAvg: 52, attendancePercent: 54, score: 50, total: 100, status: "warning" },
      ],
      weakTopics: [
        { id: "web-dev", name: "Async JavaScript & Promises", priority: "high", subject: "Web Technologies", description: "Promises, async/await and API calls" },
        { id: "java-oop", name: "Inheritance & Polymorphism", priority: "high", subject: "Java Programming", description: "OOP pillars and interface design" },
        { id: "dbms-queries", name: "Complex SQL Subqueries", priority: "high", subject: "Database Management Systems", description: "Correlated subqueries and grouping" },
      ],
      totalAssignments: 8,
      completedAssignments: 4,
      lateSubmissions: 4,
      missedQuizzes: 3,
      examsAverage: 42,
      academicRiskScore: 85,
    },
    engagementMetrics: {
      activeDaysLast30Days: 6,
      currentStreak: 0,
      longestStreak: 3,
      aiTutorInteractionsCount: 5,
      totalXP: 620,
      arenaCoins: 400,
      learningLevel: 5,
      questsCompleted: 3,
      materialsAccessedCount: 4,
      totalTimeSpentMinutes: 140,
      weeklyActiveHours: 1.2,
      engagementScore: 28,
      engagementTrend: "declining",
    },
    behaviorMetrics: {
      submissionPunctualityRate: 50,
      quizAttemptRate: 60,
      recoveryPlanAdherence: 10,
      helpSeekingFrequency: "low",
      studyConsistencyScore: 25,
      loginFrequencyPerWeek: 1,
      feedbackSubmittedCount: 0,
      behaviorScore: 35,
    },
    supportInteractions: {
      mentorRequests: [],
      supportTickets: [
        {
          id: "st_s4_1",
          creatorId: "s4",
          category: "Academic",
          description: "Request for medical leave extension",
          status: "pending",
          createdAt: "2026-09-28T09:00:00Z",
        },
      ],
      facultySessionsCount: 0,
      unresolvedIssuesCount: 3,
      mentorFeedbackCount: 0,
    },
    learningActivity: {
      recentActivities: [
        { id: "act-s4-1", type: "quiz", title: "Attempted Java OOP Quiz", detail: "Scored 38%", timestamp: "5 days ago", subject: "Java", score: 38 },
        { id: "act-s4-2", type: "assignment", title: "Assignment 3 Overdue", detail: "Not submitted", timestamp: "1 week ago", subject: "Web Technologies" },
      ],
      recoveryPlan: {
        title: "Multi-Subject Emergency Recovery Plan",
        focus: "Attendance & Core Concepts Catch-up",
        days: 14,
        tasksCompleted: 1,
        totalTasks: 14,
        progressPercent: 7,
        status: "overdue",
        currentDay: 10,
      },
      adaptiveQuizCount: 2,
      arenaBattlesCompleted: 4,
      skillsMasteredCount: 1,
    },
    trends: {
      weekly: [
        { week: "Week 1", date: "2026-08-18", quizAverage: 60, assignmentAverage: 65, attendancePercent: 72, engagementScore: 60, successScore: 64, riskScore: 38 },
        { week: "Week 2", date: "2026-08-25", quizAverage: 55, assignmentAverage: 60, attendancePercent: 68, engagementScore: 52, successScore: 58, riskScore: 46 },
        { week: "Week 3", date: "2026-09-01", quizAverage: 50, assignmentAverage: 55, attendancePercent: 62, engagementScore: 42, successScore: 51, riskScore: 58 },
        { week: "Week 4", date: "2026-09-08", quizAverage: 45, assignmentAverage: 50, attendancePercent: 58, engagementScore: 35, successScore: 45, riskScore: 70 },
        { week: "Week 5", date: "2026-09-15", quizAverage: 42, assignmentAverage: 48, attendancePercent: 54, engagementScore: 30, successScore: 42, riskScore: 80 },
        { week: "Week 6", date: "2026-09-22", quizAverage: 41, assignmentAverage: 48, attendancePercent: 52, engagementScore: 28, successScore: 40, riskScore: 85 },
      ],
      quizTrendDelta: -19,
      assignmentTrendDelta: -17,
      attendanceTrendDelta: -20,
      engagementTrendDelta: -32,
      overallDirection: "declining",
    },
    riskFactors: [
      { factorId: "rf_s4_1", category: "attendance", title: "Critical Attendance Deficit (<55%)", description: "Attendance at 52% puts student at risk of debarment", impact: "high", weight: 35, status: "active" },
      { factorId: "rf_s4_2", category: "academic", title: "Failing Quiz Averages Across 3 Courses", description: "Quiz average 41% across DBMS, Web Tech, Java", impact: "high", weight: 30, status: "active" },
      { factorId: "rf_s4_3", category: "behavior", title: "Chronic Late/Missing Submissions", description: "4 late submissions and 3 missed quizzes", impact: "high", weight: 20, status: "active" },
      { factorId: "rf_s4_4", category: "engagement", title: "Platform Disengagement", description: "Only 6 active days in last 30 days", impact: "medium", weight: 15, status: "active" },
    ],
    studentRisk: {
      overallRiskLevel: "CRITICAL",
      riskScore: 85,
      academicRisk: 85,
      attendanceRisk: 88,
      engagementRisk: 82,
      behaviorRisk: 75,
      contributingFactors: [],
      riskTrend: "worsening",
      primaryRiskDriver: "Critical attendance drop (<55%) & multi-subject failure risk",
    },
    journey: [
      { id: "je_s4_1", studentId: "s4", timestamp: "2026-08-18T09:00:00Z", date: "2026-08-18", category: "academic", title: "Semester Enrolled", description: "Enrolled in B.Tech IT 3rd Year", severity: "info" },
      { id: "je_s4_2", studentId: "s4", timestamp: "2026-09-02T11:00:00Z", date: "2026-09-02", category: "behavior", title: "Missed Assignment Deadline", description: "Web Technologies Assignment 1 missed", severity: "warning" },
      { id: "je_s4_3", studentId: "s4", timestamp: "2026-09-12T14:00:00Z", date: "2026-09-12", category: "academic", title: "Failed Java OOP Quiz", description: "Scored 38% in Java OOP mid-term quiz", severity: "critical" },
      { id: "je_s4_4", studentId: "s4", timestamp: "2026-09-20T10:00:00Z", date: "2026-09-20", category: "attendance", title: "Debarment Warning Issued", description: "Attendance dropped below 55% threshold", severity: "critical" },
    ],
    recommendedInterventions: [
      {
        id: "int_s4_1",
        studentId: "s4",
        title: "Urgent Academic Counseling & Guardian Contact",
        description: "Schedule mandatory emergency meeting with Academic Advisor, HOD & Student.",
        category: "counseling",
        suggestedBy: "AI_ENGINE",
        priority: "high",
        status: "recommended",
        createdAt: "2026-10-01T09:00:00Z",
        assignedTo: "Faculty Advisor & HOD",
      },
      {
        id: "int_s4_2",
        studentId: "s4",
        title: "Mandatory Attendance Catch-Up Contract",
        description: "Formal agreement to attend all remedial classes and daily check-ins.",
        category: "attendance_warning",
        suggestedBy: "SYSTEM",
        priority: "high",
        status: "recommended",
        createdAt: "2026-10-02T10:00:00Z",
      },
      {
        id: "int_s4_3",
        studentId: "s4",
        title: "Assigned Peer Tutor for Java & DBMS",
        description: "Pair with top-performing senior peer tutor for 3 hours per week.",
        category: "peer_study",
        suggestedBy: "AI_ENGINE",
        priority: "high",
        status: "recommended",
        createdAt: "2026-10-03T11:00:00Z",
      },
    ],
    interventionHistory: [],
    placementReadiness: {
      aptitudeScore: 44,
      codingScore: 38,
      mockInterviewScore: 40,
      resumeStatus: "not_started",
      placementAssessmentsCompleted: 1,
      preparationProgressPercent: 30,
      overallPlacementScore: 40,
      status: "needs_preparation",
    },
    lmsActivity: {
      totalLogins: 22,
      assignmentsSubmitted: 4,
      assignmentCompletionRate: 50,
      activeDaysLast30: 10,
      averageSessionDurationMins: 18,
      lastLoginDate: "2026-10-02",
      lmsScore: 45,
    },
    skillsAndFeedback: {
      technicalSkills: [
        { name: "Java Fundamentals", score: 42 },
        { name: "Web Technologies", score: 48 },
      ],
      assessmentsPassedCount: 1,
      facultyFeedbackCount: 3,
      recentFacultyNotes: "Significant attendance deficit; requires academic intervention & mentoring.",
      skillsScore: 45,
    },
    campusEngagement: {
      eventsAttendedCount: 0,
      clubParticipationsCount: 0,
      hackathonsCount: 0,
      certificationsCount: 0,
      engagementScore: 30,
    },
  },

  // -------------------------------------------------------------
  // STUDENT 5: Vikram Singh (Irregular-Engagement Student)
  // -------------------------------------------------------------
  "s5": {
    studentId: "s5",
    profile: {
      id: "s5",
      name: "Vikram Singh",
      role: "student",
      course: "B.Tech ME",
      year: "3rd Year",
      department: "Mechanical Engineering",
      attendancePercent: 76,
      quizAverage: 78,
      assignmentAverage: 81,
      lateSubmissions: 2,
      totalAssignments: 9,
      weakTopics: ["Thermodynamics", "Fluid Mechanics"],
      email: "vikram.singh@campus.edu",
      enrolledSubjects: ["Thermodynamics", "Fluid Mechanics", "Heat Transfer", "Kinematics of Machines"],
      gpa: 3.0,
      guardianContact: "+91 98765 44444",
      assignedMentorId: "f1",
      assignedMentorName: "Prof. Rahul Kumar",
      journeyType: "irregular",
    },
    successScore: 73,
    riskLevel: "MEDIUM",
    academicMetrics: {
      quizAverage: 78,
      assignmentAverage: 81,
      attendancePercent: 76,
      gpa: 3.0,
      subjectScores: [
        { subject: "Thermodynamics", quizAvg: 70, assignmentAvg: 76, attendancePercent: 72, score: 73, total: 100, status: "warning" },
        { subject: "Fluid Mechanics", quizAvg: 75, assignmentAvg: 80, attendancePercent: 75, score: 77, total: 100, status: "warning" },
        { subject: "Heat Transfer", quizAvg: 82, assignmentAvg: 84, attendancePercent: 78, score: 81, total: 100, status: "good" },
        { subject: "Kinematics of Machines", quizAvg: 85, assignmentAvg: 84, attendancePercent: 80, score: 83, total: 100, status: "good" },
      ],
      weakTopics: [
        { id: "thermo-laws", name: "Second Law of Thermodynamics & Entropy", priority: "medium", subject: "Thermodynamics", description: "Carnot cycles and entropy generation" },
        { id: "fluid-dynamics", name: "Bernoulli Equation Applications", priority: "medium", subject: "Fluid Mechanics", description: "Viscous flow and pressure drop calculations" },
      ],
      totalAssignments: 9,
      completedAssignments: 8,
      lateSubmissions: 2,
      missedQuizzes: 0,
      examsAverage: 79,
      academicRiskScore: 38,
    },
    engagementMetrics: {
      activeDaysLast30Days: 12,
      currentStreak: 1,
      longestStreak: 4,
      aiTutorInteractionsCount: 14,
      totalXP: 1950,
      arenaCoins: 1400,
      learningLevel: 13,
      questsCompleted: 10,
      materialsAccessedCount: 11,
      totalTimeSpentMinutes: 490,
      weeklyActiveHours: 4.1,
      engagementScore: 58,
      engagementTrend: "stable",
    },
    behaviorMetrics: {
      submissionPunctualityRate: 78,
      quizAttemptRate: 90,
      recoveryPlanAdherence: 50,
      helpSeekingFrequency: "moderate",
      studyConsistencyScore: 42,
      loginFrequencyPerWeek: 3,
      feedbackSubmittedCount: 1,
      behaviorScore: 60,
    },
    supportInteractions: {
      mentorRequests: [],
      supportTickets: [],
      facultySessionsCount: 1,
      lastMentorSessionDate: "2026-09-10",
      unresolvedIssuesCount: 0,
      mentorFeedbackCount: 1,
    },
    learningActivity: {
      recentActivities: [
        { id: "act-s5-1", type: "arena", title: "Binge Session: Completed 4 Arena Quests", detail: "Earned 350 XP", timestamp: "Yesterday", subject: "Fluid Mechanics" },
        { id: "act-s5-2", type: "quiz", title: "Completed Thermodynamics Quiz", detail: "Scored 72%", timestamp: "3 days ago", subject: "Thermodynamics", score: 72 },
        { id: "act-s5-3", type: "assignment", title: "Submitted Heat Transfer Assignment", detail: "Submitted on deadline", timestamp: "5 days ago", subject: "Heat Transfer" },
      ],
      recoveryPlan: {
        title: "Thermodynamics Practice Track",
        focus: "Entropy & Second Law",
        days: 7,
        tasksCompleted: 3,
        totalTasks: 7,
        progressPercent: 43,
        status: "in_progress",
        currentDay: 4,
      },
      adaptiveQuizCount: 6,
      arenaBattlesCompleted: 18,
      skillsMasteredCount: 5,
    },
    trends: {
      weekly: [
        { week: "Week 1", date: "2026-08-18", quizAverage: 82, assignmentAverage: 85, attendancePercent: 80, engagementScore: 75, successScore: 80, riskScore: 22 },
        { week: "Week 2", date: "2026-08-25", quizAverage: 70, assignmentAverage: 78, attendancePercent: 72, engagementScore: 40, successScore: 65, riskScore: 42 },
        { week: "Week 3", date: "2026-09-01", quizAverage: 84, assignmentAverage: 84, attendancePercent: 78, engagementScore: 80, successScore: 81, riskScore: 25 },
        { week: "Week 4", date: "2026-09-08", quizAverage: 68, assignmentAverage: 76, attendancePercent: 70, engagementScore: 35, successScore: 62, riskScore: 48 },
        { week: "Week 5", date: "2026-09-15", quizAverage: 80, assignmentAverage: 82, attendancePercent: 78, engagementScore: 78, successScore: 78, riskScore: 28 },
        { week: "Week 6", date: "2026-09-22", quizAverage: 78, assignmentAverage: 81, attendancePercent: 76, engagementScore: 58, successScore: 73, riskScore: 35 },
      ],
      quizTrendDelta: -4,
      assignmentTrendDelta: -4,
      attendanceTrendDelta: -4,
      engagementTrendDelta: -17,
      overallDirection: "stable",
    },
    riskFactors: [
      { factorId: "rf_s5_1", category: "behavior", title: "Erratic Study Pattern", description: "Alternates between total inactivity and burst studying", impact: "medium", weight: 20, status: "active" },
      { factorId: "rf_s5_2", category: "attendance", title: "Fluctuating Class Attendance", description: "Attendance swings between 70% and 80%", impact: "medium", weight: 15, status: "active" },
    ],
    studentRisk: {
      overallRiskLevel: "MEDIUM",
      riskScore: 35,
      academicRisk: 38,
      attendanceRisk: 35,
      engagementRisk: 42,
      behaviorRisk: 40,
      contributingFactors: [],
      riskTrend: "stable",
      primaryRiskDriver: "Inconsistent study habits & burst activity pattern",
    },
    journey: [
      { id: "je_s5_1", studentId: "s5", timestamp: "2026-08-18T09:00:00Z", date: "2026-08-18", category: "academic", title: "Semester Enrolled", description: "Enrolled in B.Tech ME 3rd Year", severity: "info" },
      { id: "je_s5_2", studentId: "s5", timestamp: "2026-08-28T14:00:00Z", date: "2026-08-28", category: "engagement", title: "Inactivity Spike Recorded", description: "0 platform logins recorded for 5 consecutive days", severity: "warning" },
      { id: "je_s5_3", studentId: "s5", timestamp: "2026-09-02T18:00:00Z", date: "2026-09-02", category: "engagement", title: "Burst Study Surge", description: "Completed 4 Arena quests and 2 quizzes in single evening", severity: "positive" },
    ],
    recommendedInterventions: [
      {
        id: "int_s5_1",
        studentId: "s5",
        title: "Study Pace Regularization & Micro-Habit Plan",
        description: "Set up daily 20-minute micro-mission goals to smooth out study spikes.",
        category: "recovery_plan",
        suggestedBy: "AI_ENGINE",
        priority: "medium",
        status: "recommended",
        createdAt: "2026-10-02T10:00:00Z",
      },
      {
        id: "int_s5_2",
        studentId: "s5",
        title: "Automated Calendar Deadline Push Notifications",
        description: "Configure SMS/Push alerts 48h and 24h prior to assignment deadlines.",
        category: "attendance_warning",
        suggestedBy: "SYSTEM",
        priority: "low",
        status: "recommended",
        createdAt: "2026-10-03T10:00:00Z",
      },
    ],
    interventionHistory: [],
    placementReadiness: {
      aptitudeScore: 82,
      codingScore: 86,
      mockInterviewScore: 48,
      resumeStatus: "in_progress",
      placementAssessmentsCompleted: 3,
      preparationProgressPercent: 58,
      overallPlacementScore: 65,
      status: "needs_preparation",
    },
    lmsActivity: {
      totalLogins: 34,
      assignmentsSubmitted: 8,
      assignmentCompletionRate: 88,
      activeDaysLast30: 12,
      averageSessionDurationMins: 38,
      lastLoginDate: "2026-10-08",
      lmsScore: 72,
    },
    skillsAndFeedback: {
      technicalSkills: [
        { name: "Python Scripting", score: 88 },
        { name: "CAD & FEA Modeling", score: 82 },
        { name: "Thermodynamics", score: 75 },
      ],
      assessmentsPassedCount: 5,
      facultyFeedbackCount: 1,
      recentFacultyNotes: "Solid engineering intuition; needs resume review & behavioral mock interview.",
      skillsScore: 82,
    },
    campusEngagement: {
      eventsAttendedCount: 2,
      clubParticipationsCount: 1,
      hackathonsCount: 2,
      certificationsCount: 1,
      engagementScore: 65,
    },
  },

  // -------------------------------------------------------------
  // STUDENT 6: Sneha Patel (New Admitted / Incomplete Data Profile)
  // Demonstrates dynamic missing-data handling, coverage indicator,
  // weight re-normalization, and "Insufficient Data" classification.
  // -------------------------------------------------------------
  "s6": {
    studentId: "s6",
    profile: {
      id: "s6",
      name: "Sneha Patel",
      role: "student",
      course: "B.Tech AI&DS",
      year: "1st Year",
      department: "Artificial Intelligence & Data Science",
      attendancePercent: 88,
      quizAverage: 65,
      assignmentAverage: 70,
      lateSubmissions: 0,
      totalAssignments: 2,
      weakTopics: ["Python Basics"],
      email: "sneha.patel@campus.edu",
      enrolledSubjects: ["Python for AI", "Calculus & Linear Algebra", "Digital Principles"],
      gpa: 3.1,
      guardianContact: "+91 98765 55555",
      assignedMentorId: "f1",
      assignedMentorName: "Prof. Rahul Kumar",
      journeyType: "stable",
    },
    successScore: 0, // Calculated dynamically
    riskLevel: "LOW",
    academicMetrics: {
      quizAverage: 65,
      assignmentAverage: 70,
      attendancePercent: 88,
      gpa: 3.1,
      subjectScores: [
        { subject: "Python for AI", quizAvg: 68, assignmentAvg: 72, attendancePercent: 90, score: 70, total: 100, status: "good" },
        { subject: "Calculus & Linear Algebra", quizAvg: 62, assignmentAvg: 68, attendancePercent: 86, score: 65, total: 100, status: "warning" },
      ],
      weakTopics: [
        { id: "python-basics", name: "Python Control Flow & Loops", priority: "low", subject: "Python for AI", description: "While loops and list comprehensions" },
      ],
      totalAssignments: 2,
      completedAssignments: 2,
      lateSubmissions: 0,
      missedQuizzes: 0,
      examsAverage: 66,
      academicRiskScore: 30,
    },
    engagementMetrics: {
      activeDaysLast30Days: 4,
      currentStreak: 1,
      longestStreak: 2,
      aiTutorInteractionsCount: 3,
      totalXP: 450,
      arenaCoins: 300,
      learningLevel: 3,
      questsCompleted: 2,
      materialsAccessedCount: 2,
      totalTimeSpentMinutes: 90,
      weeklyActiveHours: 1.2,
      engagementScore: 40,
      engagementTrend: "stable",
    },
    behaviorMetrics: {
      submissionPunctualityRate: 100,
      quizAttemptRate: 100,
      recoveryPlanAdherence: 0,
      helpSeekingFrequency: "low",
      studyConsistencyScore: 50,
      loginFrequencyPerWeek: 2,
      feedbackSubmittedCount: 0,
      behaviorScore: 70,
    },
    supportInteractions: {
      mentorRequests: [],
      supportTickets: [],
      facultySessionsCount: 0,
      unresolvedIssuesCount: 0,
      mentorFeedbackCount: 0,
    },
    learningActivity: {
      recentActivities: [],
      recoveryPlan: {
        title: "Freshman Transition",
        focus: "Orientation",
        days: 7,
        tasksCompleted: 1,
        totalTasks: 5,
        progressPercent: 20,
        status: "in_progress",
        currentDay: 2,
      },
      adaptiveQuizCount: 1,
      arenaBattlesCompleted: 0,
      skillsMasteredCount: 1,
    },
    trends: {
      weekly: [
        { week: "Week 1", date: "2026-10-01", quizAverage: 65, assignmentAverage: 70, attendancePercent: 88, engagementScore: 40, successScore: 68, riskScore: 20 },
      ],
      quizTrendDelta: 0,
      assignmentTrendDelta: 0,
      attendanceTrendDelta: 0,
      engagementTrendDelta: 0,
      overallDirection: "stable",
    },
    riskFactors: [],
    studentRisk: {
      overallRiskLevel: "LOW",
      riskScore: 22,
      academicRisk: 30,
      attendanceRisk: 15,
      engagementRisk: 35,
      behaviorRisk: 20,
      contributingFactors: [],
      riskTrend: "stable",
      primaryRiskDriver: "Insufficient baseline historical data",
    },
    journey: [
      { id: "je_s6_1", studentId: "s6", timestamp: "2026-10-01T09:00:00Z", date: "2026-10-01", category: "academic", title: "Freshman Onboarding", description: "Enrolled in B.Tech AI&DS", severity: "info" },
    ],
    recommendedInterventions: [],
    interventionHistory: [],
    // Intentionally omit placementReadiness, lmsActivity, skillsAndFeedback, campusEngagement
    // to test and demonstrate missing data handling!
  },
};

